### PR TITLE
Nsbranch

### PR DESCRIPTION
**Pull request by Haotian9850**
merge Neil's branch to development

### CODE REVIEW

**Comment by ns9wr** [comment]
My code freaks out when I try to use Hao's config file

**Comment by qdegroot** [comment]
Wait, so are we collaboratively correcting this or something? Current version is a bit broken

**Comment by ns9wr** [comment]
I ~think~ what bugs there are should behave now. How do I test this inside the server? I tried and I get Internal Server Error 500

**Comment by qdegroot** [comment]
So I just pulled this branch to my machine, and the first thing I noticed was in `$sql="INSERT INTO Review (text, rating) VALUES('$_POST[inputtext]','$_POST[inputrate]')";` in review_service, inputtext and inputrate didn't have quotes around them. Plus it would be better to use the ->prepare() convention we've been using in registration_service and stuff like that to avoid sql injection issues anyway

**Comment by Haotian9850** [comment]
> So I just pulled this branch to my machine, and the first thing I noticed was in `$sql="INSERT INTO Review (text, rating) VALUES('$_POST[inputtext]','$_POST[inputrate]')";` in review_service, inputtext and inputrate didn't have quotes around them. Plus it would be better to use the ->prepare() convention we've been using in registration_service and stuff like that to avoid sql injection issues anyway

good suggestion!

**Comment by ns9wr** [comment]
I would like to see this functioning with Hao's file system on the web before making the aforementioned changes----good eye Quintin

**Pull request merged**
